var dictionary =  [

    { word:"私"             ,yomi:"わたし"              ,mean:["ကျွန်တော်", "ကျွန်မ"]  ,remark:"(ယဥ်ကျေးသောအသုံးအနုံး)"},
    { word:" 貴方"          ,yomi:"あなた "             ,mean:["သင်", "ခင်ဗျား" ]     ,remark:""},
    { word:"先生"           ,yomi:" せんせい"            ,mean:["ဆရာ","ဆရာမ"]     ,remark:""},
    { word:"医者"           ,yomi:"いしゃ "              ,mean:["ဆရာဝန်"]            ,remark:""},
    { word:" 会社"         ,yomi:"かいしゃ "                ,mean:["ကုမ္ပဏီ"]            ,remark:""},
    { word:"日本"           ,yomi:"にほん"                  ,mean:["ဂျပန်"]              ,remark:""},
    { word:"何"             ,yomi:"なに"                    ,mean:["ဘာလဲ"]                ,remark:""}, 
    { word:"初めまして"     ,yomi:["はじめまして"]           ,mean:["ပထမဆုံးအနေဖြင့်"]         ,remark:"(စတင်မိတ်ဆက်ရာမှာသုံးသည်)" },
    { word:"こちらは"       ,yomi:["こちらは"]               ,mean:["ဒီဘက်ကလူကတော့"]         ,remark:""},
    { word:"おはよう御座います" ,yomi:["おはようございます"]   ,mean:["မင်္ဂလာနံနက်ခင်းပါ"]          ,remark:""},
    { word:"アメリカ"           ,yomi:["america"]              ,mean:["အမေရိက"]               ,remark:""},
    { word:"どうぞよろしく"     ,yomi:["どうぞよろしく"]         ,mean:["တွေ့ရတာဝမ်းသာပါတယ်"]   ,remark:""},
    { word:"会社員"             ,yomi:["かいしゃいん"]          ,mean:["ကုမ္ပဏီဝန်ထမ်း"]          ,remark:""},
    { word:"エンジニア"         ,yomi:"engineer"               ,mean:["အင်ဂျင်နီယာ"]            ,remark:""},
    { word:"あの方"             ,yomi:["あのかた"]              ,mean:["အဲဒီလူ"]                ,remark:"(ယဥ်ကျေးသောအသုံးအနုံး)"},
    { word:"誰"                 ,yomi:["だれ"]                 ,mean:["ဘယ်သူ"]                ,remark:""},
    { word:"何方"             ,yomi:["どなた"]                ,mean:["ဘယ်သူ" ]              ,remark:"(ယဥ်ကျေးသောအသုံးအနုံး)"},
    { word:"ブラジル"           ,yomi:["brazil"]              ,mean:["ဘရာဇီး"]                 ,remark:""},
    { word:"人"                 ,yomi:["じん"]                 ,mean:["လူမျိုး"]                ,remark:""},
    { word:"大学"               ,yomi:["だいがく"]             ,mean:["တက္ကသိုလ်"]              ,remark:""},
    { word:"大学生"             ,yomi:["だいがくせい"]          ,mean:["တက္ကသိုလ်ကျောင်းသား"]     ,remark:""},
    { word:"学校"               ,yomi:["がっこう"]             ,mean:["ကျောင်း"]                ,remark:""},
    { word:"学生"               ,yomi:["がくせい"]             ,mean:["ကျောင်းသား","ကျောင်းသူ"]   ,remark:""},
    { word:"歳"                 ,yomi:["さい"]                 ,mean:["အသက်"]                  ,remark:"(အသက်အရွယ်)"},
    { word:"おいくつ"           ,yomi:["おいくつ"]            　,mean:["အသက်"]               　,remark:"(ယဥ်ကျေးသောအသုံးအနုံး)"},
    { word:"銀行員"             ,yomi:["ぎんこういん"]          ,mean:["ဘဏ်ဝန်ထမ်း"]             ,remark:""},
    { word:"社員"               ,yomi:["しゃいん"]             ,mean:["ဝန်ထမ်း"]                  ,remark:""},
    { word:"です"               ,yomi:"です "                 ,mean:["ဖြစ်သည်"]                  ,remark:""},
    { word:"ですか"             ,yomi:"ですか "                ,mean:["ဖြစ်ပါသလား"]               ,remark:""},
    { word:"ではありません"      ,yomi:["ではありません"]       ,mean:["မဟုတ်ပါဘူး"]               ,remark:"(ယဥ်ကျေးသောအသုံးအနုံး)"},
    { word:"じゃありません"      ,yomi:["じゃありません"]       ,mean:["မဟုတ်ပါဘူး"]               ,remark:""},
    { word:"名前"               ,yomi:["なまえ"]                ,mean:["နာမည်"]                  ,remark:""},
    { word:"失礼ですが"          ,yomi:["しつれいですが"]       ,mean:["စိတ်မရှိပါနဲ့"]                ,remark:""},
    { word:"来ました"            ,yomi:["きました"]             ,mean:["လာခဲ့ပါတယ်"]               ,remark:""},
    { word:"パワー電気"          ,yomi:["パワーでんき"]         ,mean:["ပါဝါလျှပ်စစ်ကုမ္ပဏီ"]          ,remark:"(ကုမ္ပဏီနာမည်)"},
    { word:"教師"               ,yomi:["きょうし" ]             ,mean:["ကျောင်းဆရာ"]               ,remark:"(ဝန်ထမ်းအလုပ်)"},
    { word:"IMC"                ,yomi:["IMC"]                 ,mean:["IMCကုမ္ပဏီ"]                 ,remark:"(ကုမ္ပဏီနာမည်)"},
    { word:"何歳ですか"          ,yomi:["なんさいですか"]       ,mean:["အသက်ဘယ်လောက်လဲ"]                          ,remark:""},
    { word:"おいくつですか"      ,yomi:["おいくつですか"]        ,mean:["အသက်ဘယ်နှနှစ်လဲ"]                            ,remark:"(ယဥ်ကျေးသောအသုံးအနုံး)"},
    { word:"これ"                       ,yomi:"これ"                                ,mean:["ဒီဟာ"]                    ,remark:""},
    { word:"それ"                       ,yomi:"それ"                                ,mean:["အဲ့ဒီဟာ"]                  ,remark:""},
    { word:"あれ"                       ,yomi:"あれ"                                ,mean:["ဟိုဟာ"]                   ,remark:""},
    { word:"この"                       ,yomi:"この"                                ,mean:["ဒီ"]                     ,remark:"ဒီ~"},
    { word:"その"                       ,yomi:"その"                                ,mean:["အဲ့ဒီ"]                    ,remark:"အဲ့ဒီ~"},
    { word:"あの"                       ,yomi:"あの"                                ,mean:["ဟို"]                     ,remark:"ဟို~"},
    { word:"辞書"                       ,yomi:"じしょ"                              ,mean:["အဘိဓာန်"]                 ,remark:""},
    { word:"コンピューター"             ,yomi:"computer"                            ,mean:["ကွန်ပျူတာ"]                 ,remark:""},
    { word:"傘"                         ,yomi:"かさ"                                 ,mean:["ထီး"]                    ,remark:""},
    { word:"テレホンカード"             ,yomi:"telephone card"                      ,mean:["တယ်လီဖုန်းကဒ်"]             ,remark:""},
    { word:"本"                         ,yomi:"ほん"                                 ,mean:["စာအုပ်"]                  ,remark:""},
    { word:"ノート"                     ,yomi:"note"                                 ,mean:["မှတ်စုစာအုပ်"]               ,remark:""},
    { word:"手帳"                       ,yomi:"てちょう"                            ,mean:["လက်ကိုင်စာအုပ်"]              ,remark:""},
    { word:"名刺"                       ,yomi:"めいし"                              ,mean:["လိပ်စာကဒ်"]                ,remark:""},
    { word:"雑誌"                       ,yomi:"ざっし"                              ,mean:["မဂ္ဂဇင်း","စာစောင်"]            ,remark:""},
    { word:"自動車"                     ,yomi:"じどうしゃ"                          ,mean:["မော်တော်ကား"]               ,remark:""},
    { word:"鞄"                         ,yomi:"かばん"                              ,mean:["အိတ်"]                    ,remark:"(ခရီးဆောင်အိတ် ကဲ့သို့ အိတ်)"},
    { word:"鍵"                         ,yomi:"かぎ"                                ,mean:["သော့"]                    ,remark:""},
    { word:"鉛筆"             　　      ,yomi:"えんぴつ"                        　　,mean:["ခဲတံ"]              ,remark:""},
    { word:"チョコレート"             　,yomi:"chocolate"                           ,mean:["ချောကလက်"]              ,remark:""},
    { word:"コーヒー"                   ,yomi:"coffee"                              ,mean:["ကော်ဖီ"]                             ,remark:""},
    { word:"新聞"             　　      ,yomi:"しんぶん"                            ,mean:["သတင်းစာ"]              ,remark:""},
    { word:"ボールペン"             　　 ,yomi:"ballpen"                            ,mean:["ဘောပင်"]              ,remark:""},
    { word:"日本語"             　　    ,yomi:"にほんご"                            ,mean:["ဂျပန်စာ"]              ,remark:""},
    { word:"机"             　　        ,yomi:"つくえ"                              ,mean:["စားပွဲ"]              ,remark:""},
    { word:"シャープペンシル"           ,yomi:"sharp pencil"                        ,mean:["ဘောပင်ခဲတံ"]              ,remark:"mechanical pencil"},
    { word:"時計"             　　      ,yomi:"とけい"                          　　,mean:["နာရီ"]              ,remark:""},
    { word:"カメラ"             　　    ,yomi:"camera"                              ,mean:["ကင်မရာ"]              ,remark:""},
    { word:"椅子"             　　      ,yomi:["いす"]                              ,mean:["ကုလားထိုင်","ခုံ"]              ,remark:""},
    { word:"テープ"             　　    ,yomi:"tape"                               ,mean:["တိပ်ခွေ"]              ,remark:""},
    { word:"英語"             　　      ,yomi:"えいご"                              ,mean:["အင်္ဂလိပ်စာ"]              ,remark:""},
    { word:"韓国"             　　      ,yomi:"かんこく"                            ,mean:["ကိုရီးယား"]              ,remark:""},
    { word:"韓国語"             　　    ,yomi:"かんこくご"                          ,mean:["ကိုရီးယားစာ"]              ,remark:""},
    { word:"今日は"                     ,yomi:"こんにちは"                          ,mean:["မင်္ဂလာနေ့လည်ခင်း"]           ,remark:""},
    { word:"これから"                   ,yomi:"これから"                        　　,mean:["အခုမှစပြီး"]                  , remark:""},
    { word:"これからお世話になります"   　,yomi:"これからおせわになります"             ,mean:["အခုချိန်မှစပြီကူညီစောင့်ရှောက်ပေးပါခင်ဗျာ"]                ,remark:"(တဖက်လူကိုမိမိကိုယ်ကိုမိတ်ဆက်ပြီးပြောရာမှာသုံးသည်)"},
    { word:"どうぞよろしくお願いします" 　,yomi:["どうぞよろしくおねがいします"]        ,mean:["တွေ့ရတာဝမ်းသာပါတယ်","ကူညီစောင့်ရှောက်ပေးပါခင်ဗျာ"]     ,remark:"(ပိုမိုယဥ်ကျေးအောင်ပြောဆိုရာမှာသုံးသည်)"},
    { word:"こちらこそ宜しく"          　,yomi:"こちらこそよろしく"                   ,mean:["ဒီကလည်းပဲတွေ့ရတာဝမ်းသာပါတယ်"]                     ,remark:"(မိမိဘက်မှတွေ့ရတာ ဝမ်းသာကြောင်းပြောတဲ့အခါမှာသုံးသည်)"},
    { word:"本の気持ちです"　　         　,yomi:"ほんのきもちです"                    ,mean:["စိတ်ရင်းဖြင့်ပါ"]    ,remark:"(လက်ဆောင်ပေးရာတွင် သုံးသည်)"},
    { word:"何ですか"                   ,yomi:"なんですか"                          ,mean:["ဘာလဲ","ဘာများလဲ"]          ,remark:""},
    { word:"どうぞ"             　　    ,yomi:"どうぞ"                              ,mean:["လက်ခံပေးပါ"]              ,remark:"(どうぞသည် တစ်ဖက်လူအား ဦးစားပေးလုပ်ဆောင်စေချင်သည့် အခါ၊ လက်ခံစေချင်သည်အခါမှာ သုံးသည်)"},
    { word:"どうも"             　　    ,yomi:"どうも"                              ,mean:["ကျေးဇူးတင်ပါတယ်"]                   ,remark:""},
    { word:"どうも有難う御座います"      ,yomi:"どうもありがとうございます"         　　,mean:["အရမ်းကျေးဇူးတင်ပါတယ်"]              ,remark:"(လေးလေးနက်နက်ပြောရာမှာသုံးသည်)"},
    { word:"違います"             　　  ,yomi:"ちがいます"                      　　,mean:["မဟုတ်ပါဘူး"]              ,remark:""},
    { word:"そうです"             　　  ,yomi:"そうです"              　　　　　　　,mean:["ဟုတ်ပါတယ်"]              ,remark:""},
    { word:"そうですか"             　　  ,yomi:"そうですか"              　　　　　,mean:["ဟုတ်လား"]              ,remark:""},
    { word:"ここ"  　   ,yomi:"ここ"  　　　,mean:["ဒီနေရာ"]             　　　,remark:""},  　　　　　　　
{ word:"そこ"  　   ,yomi:"そこ"  　　　,mean:["ဟိုနေရာ"]               　　,remark:""},  　　　　　　　　　　　　
{ word:"あそこ"   　,yomi:"あそこ"  　　,mean:["ဟိုးနေရာ"]               　,remark:""},  　　　　　　　　　　　　　
{ word:"どこ"  　   ,yomi:"どこ"  　　　,mean:["ဘယ်နေရာ"]               　　,remark:""},  　　　　　　　　　　　　
{ word:"こちら"  　 ,yomi:"こちら"  　  ,mean:["ဒီဖက်","ဒီနေရာ"]         ,remark:"ယဉ်ကျေးသောအသုံးအနှုန်း"},

{ word:"そちら" 　  ,yomi:"そちら"  　    ,mean:["ဟိုဖက်","ဟိုနေရာ"]       ,remark:"ယဉ်ကျေးသောအသုံးအနှုန်း"},

{ word:"あちら" 　  ,yomi:"あちら"  　    ,mean:["ဟိုးဖက်","ဟိုးနေရာ"]      ,remark:"ယဉ်ကျေးသောအသုံးအနှုန်း"},

{ word:"どちら"     ,yomi:"どちら"         ,mean:["ဘယ်ဖက်","ဘယ်နေရာ"]    ,remark:"ယဉ်ကျေးသောအသုံးအနှုန်း"},
{ word:"教室"  　   ,yomi:"きょうしつ"  　　　,mean:["စာသင်ခန်း"]               　　　　　　　,remark:""},
{ word:"食堂"  　   ,yomi:"しょくどう"  　　　,mean:["ထမင်းစားခန်း","ကန်တင်း"]            ,remark:""},
{ word:"事務所"  　 ,yomi:"じむしょ"  　　　,mean:["ရုံးခန်း"]               　　　　　　　,remark:""},
{ word:"会議室"  　 ,yomi:"かいぎしつ"  　　　,mean:["အစည်းအဝေးခန်း"]               　　　,remark:""},
{ word:"受付"  　   ,yomi:"うけつけ"  　　　,mean:["ဧည့်ကြိုစားပွဲ"]               　　　　　　　,remark:""},
{ word:"ロビー"  　 ,yomi:"lobby"  　　　,mean:["ဧည့်ခန်း"]               　　　　　　　,remark:""},
{ word:"部屋"  　   ,yomi:"へや"  　　　,mean:["အခန်း"]               　　　　　　　,remark:""},
{ word:"トイレ"  　 ,yomi:"toilet"  　　　,mean:["သန့်စင်ခန်း"]               　　　　　　　,remark:""},
{ word:"御手洗い"  　,yomi:"おてあらい"  　　　,mean:["သန့်စင်ခန်း"]               　　　　　　,remark:""},

{ word:"階段"  　   ,yomi:"かいだん"  　　　,mean:["လှေကား"]               　　　　　　　,remark:""},

{ word:"エレベーター"  　,yomi:"elevator"  　　　,mean:["ဓါတ်လှေကား"]               　　　,remark:""},

{ word:"エスカレーター"  　,yomi:"escalator"  　　　,mean:["စက်လှေကား"]               　　,remark:""},
{ word:"自動販売機"     ,yomi:"じどうはんばいき" ,mean:["အလိုအလျောက်ရောင်းချသောစက်"] ,remark:""},
{ word:"電話"  　   ,yomi:"でんわ"  　　　,mean:["တယ်လီဖုန်း"]               　　　　　　,remark:""},
{ word:"お国"  　   ,yomi:"おくに"  　　　,mean:["နိုင်ငံ"]               　　　　　　　,remark:""},
{ word:"会社"  　   ,yomi:"かいしゃ"  　　　,mean:["ကုမ္မဏီ"]               　　　　　　　,remark:""},
{ word:"家"  　     ,yomi:"うち"  　　　,mean:["အိမ်"]               　　　　　　　,remark:""},
{ word:"靴"  　     ,yomi:"くつ"  　　　,mean:["ဖိနပ်"]               　　　　　　　,remark:""},

{ word:"ネクタイ"  　,yomi:"necktie"  　　,mean:["နက်ကတိုင်","လည်စည်း"]            ,remark:""},

{ word:"ワイン"  　,yomi:"wine"  　　　,mean:["ဝိုင်"]               　　　　　　　,remark:""},

{ word:"売り場"  　,yomi:"うりば"  　　　,mean:["အရောင်းဆိုင်"]               　　　　　　　,remark:""},
{ word:"地下"  　,yomi:"ちか"  　　　,mean:["မြေအောက်"]               　　　　　　　,remark:""},
{ word:"ー階"  　,yomi:"いっかい"  　　　,mean:["တစ်ထပ်"]               　　　　　　　,remark:""},
{ word:"何階"  　,yomi:"なんがい"  　　　,mean:["ဘယ်နှစ်ထပ်"]               　　　　　　　,remark:""},
{ word:"―円"  　,yomi:"―えん"  　　　,mean:["―ယန်း"]               　　　　　　　,remark:""},

{ word:"幾ら"  　,yomi:"いくら"  　　　,mean:["ဘယ်လောက်"]               　　　　　　　,remark:""},
{ word:"百"  　,yomi:"ひゃく"  　　　,mean:["ရာ"]               　　　　　　　,remark:""},

{ word:"千"  　,yomi:"せん"  　　　,mean:["ထောင်"]               　　　　　　　,remark:""},

{ word:"万"  　,yomi:"まん"  　　　,mean:["သောင်း"]               　　　　　　　,remark:""},


 ];
